### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by ammar-n-abbas** [joyjitchatterjee/DeepRLTurbineVesselTransfer#1]
Hello,

Where to find the dataset: 'df_ldt_per_engie_final.pkl'?

**Comment by joyjitchatterjee** [comment]
Hi there,
Thanks for your message - the file is unfortunately confidential and not publicly available.

**Comment by ammar-n-abbas** [comment]
okay, thanks for the reply

**Comment by joyjitchatterjee** [comment]
No problem. I can refer you to a webpage which might be helpful for you: this contains open wind farm data from an onshore wind farm in case you wanted something similar to explore and is publicly available. But there are no labelled fault records though, it only contains SCADA features and Met Data. https://opendata-renewables.engie.com/explore/index

**Comment by ammar-n-abbas** [comment]
Thank you very much...
